#! /bin/sh
### BEGIN INIT INFO
# Provides:          statsfeeder
# Required-Start:    $network $named $remote_fs $syslog
# Required-Stop:     $network $named $remote_fs $syslog
# Should-Start:      StatsFeeder.sh
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

[ -r /etc/default/statsfeeder ] && . /etc/default/statsfeeder

. /lib/lsb/init-functions

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=StatsFeeder.sh
DAEMON_OPTS=$OPTS
NAME=statsfeeder
CWD=$INSTALL_DIR
DESC="vCenter $NAME wrapper"
PIDFILE="/var/run/${NAME}.pid"

test -x $CWD/$DAEMON || exit 0

is_true() {
    if [ "x$1" = "xtrue" -o "x$1" = "xyes" -o "x$1" = "x0" ] ; then
       return 0
    else
        return 1
    fi
}

start_statsfeeder() {
    if is_true "$START" ; then
        start-stop-daemon --start --quiet --pidfile $PIDFILE \
          --chdir $CWD --make-pidfile --background --startas $DAEMON -- $DAEMON_OPTS
    else
        echo ""
        echo "$NAME not configured to start, please edit /etc/default/$NAME to enable"
    fi
}

stop_statsfeeder() {
    CPID=`pgrep -P $(cat $PIDFILE)`
    kill -15 $CPID
    start-stop-daemon --stop --retry TERM/10/KILL/5 --quiet --oknodo --pidfile $PIDFILE
}

status_statsfeeder() {
    if (type status_of_proc > /dev/null 2>&1) ; then
        status_of_proc -p "${PIDFILE}" "${DAEMON}" "${NAME}"
    else
        status_of_proc() {
            local pidfile daemon name status

            pidfile=
            OPTIND=1
            while getopts p: opt ; do
                case "$opt" in
                    p)  pidfile="$OPTARG";;
                esac
            done
            shift $(($OPTIND - 1))

            if [ -n "$pidfile" ]; then
                pidfile="-p $pidfile"
            fi
            daemon="$1"
            name="$2"
            status="0"
            pidofproc $pidfile $daemon >/dev/null || status="$?"
            if [ "$status" = 0 ]; then
                log_success_msg "$name is running"
                return 0
            elif [ "$status" = 4 ]; then
                log_failure_msg "could not access PID file for $name"
                return $status
            else
                log_failure_msg "$name is not running"
                return $status
            fi
        }
        status_of_proc -p "${PIDFILE}" "${DAEMON}" "${NAME}"
    fi
}

case "$1" in
    start)
        log_begin_msg "Starting $DESC"
        start_statsfeeder
        log_end_msg $?
    ;;
    stop)
        log_begin_msg "Stopping $DESC"
        stop_statsfeeder
        log_end_msg $?
    ;;
    status)
        status_statsfeeder
    ;;
    restart|force-reload)
        log_begin_msg "Restarting $DESC"
        stop_statsfeeder
        start_statsfeeder
        log_end_msg $?
    ;;
    *)
        echo "Usage: $0 {start|stop|status|restart|force-reload}" >&2
        exit 1
    ;;
esac
